---

certbot_enabled: false
certbot_install_dir: /opt/certbot
certbot_package_name: certbot
certbot_http_certs: {}
certbot_http_port: 40404
certbot_http_dns_wait_retries: 3
certbot_http_dns_wait_delay: 10
certbot_dns_nicru_enabled: false
certbot_dns_nicru_package_version: 1.0.3
certbot_dns_nicru_credentials_dir: /etc/letsencrypt/.secrets
certbot_dns_nicru_credentials_path: '{{ certbot_dns_nicru_credentials_dir }}/nicru.ini'
certbot_dns_nicru_propagation_seconds: 300
certbot_dns_nicru_client_id: ~
certbot_dns_nicru_client_secret: ~
certbot_dns_nicru_username: ~
certbot_dns_nicru_password: ~
certbot_dns_nicru_scope: ~
certbot_dns_nicru_service: ~
certbot_dns_nicru_zone: ~
certbot_email: ~
certbot_server: https://acme-v02.api.letsencrypt.org/directory
certbot_rsa_key_size: 4096
certbot_haproxy_deploy_hook_enabled: false
certbot_haproxy_cert_dir: /etc/ssl/haproxy
certbot_haproxy_cert_owner: haproxy
certbot_haproxy_cert_group: haproxy
certbot_haproxy_spread_targets: []
certbot_haproxy_spread_ssh_user: ''
certbot_haproxy_spread_ssh_private_key_file: ~
certbot_haproxy_spread_ssh_dir: '{{ certbot_install_dir }}/ssh'
certbot_haproxy_spread_ssh_private_key_path: '{{ certbot_haproxy_spread_ssh_dir }}/haproxy-spread'
certbot_haproxy_spread_ssh_known_hosts_path: '{{ certbot_haproxy_spread_ssh_dir }}/known_hosts'
certbot_haproxy_spread_ssh_connect_timeout: 10
certbot_haproxy_spread_ssh_strict_host_key_checking: accept-new
certbot_haproxy_spread_wildcards_only: true
certbot_renew_timer_enabled: true
certbot_renew_on_calendar: '*-*-* 00,12:00:00'
certbot_renew_randomized_delay_sec: 1h
