---

docker_jaeger_config_template: config.yaml.j2
docker_jaeger_http_port: 16686
docker_jaeger_image_name: jaegertracing/jaeger
docker_jaeger_image_tag: 2.19.0
docker_jaeger_image_full: '{{ docker_jaeger_image_name }}:{{ docker_jaeger_image_tag }}'
docker_jaeger_data_volume: jaeger-data
docker_jaeger_mem_res: 500M
docker_jaeger_mem_lim: 750M
docker_jaeger_mem_swp: 1000M
docker_jaeger_otlp_grpc_port: 4319
docker_jaeger_otlp_http_port: 4320
