---

docker_swarm_traefik_letsencrypt_enabled: "{{ docker_swarm_traefik_letsencrypt_email is not none and docker_swarm_traefik_letsencrypt_email | string | length > 0 }}"
docker_swarm_traefik_manager_only_enabled: "{{ 'node.role == manager' in docker_swarm_traefik_placement_constraints }}"
docker_swarm_traefik_dashboard_rule: >-
  {{
    '('
    ~ (docker_swarm_traefik_domains | map('regex_replace', '^(.*)$', 'Host(`\1`)') | join(' || '))
    ~ ') && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
  }}
docker_swarm_traefik_ping_paths: >-
  {{
    ([docker_swarm_traefik_ping_path] + docker_swarm_traefik_ping_alias_paths)
    | map('string')
    | map('trim')
    | unique
    | list
  }}
docker_swarm_traefik_ping_rule: "{{ docker_swarm_traefik_ping_paths | map('regex_replace', '^(.*)$', 'Path(`\\1`)') | join(' || ') }}"
docker_swarm_traefik_published_ports: >-
  {{
    [
      {
        'published_port': docker_swarm_traefik_http_expose_port,
        'target_port': 80,
        'protocol': 'tcp',
        'mode': 'host',
      },
      {
        'published_port': docker_swarm_traefik_https_expose_port,
        'target_port': 443,
        'protocol': 'tcp',
        'mode': 'host',
      },
    ]
  }}
