---

- name: Ensure root user has correct settings and password
  become: true
  ansible.builtin.user:
    name: root
    password: '{{ iam_master_password_hash }}'
    shell: /bin/bash
  no_log: '{{ iam_nolog }}'

- name: Update /etc/skel/.bashrc
  become: true
  ansible.builtin.copy:
    src: skel/bashrc.sh
    dest: /etc/skel/.bashrc
    mode: '0644'

- name: Update /root/.bashrc
  become: true
  ansible.builtin.copy:
    src: skel/bashrc.sh
    dest: /root/.bashrc
    owner: root
    group: root
    mode: '0644'
