---

- name: Ensure GitLab runner config directory exists
  become: true
  ansible.builtin.file:
    path: '{{ gitlab_runner_config_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Write GitLab runner config
  become: true
  ansible.builtin.template:
    src: config.toml.j2
    dest: '{{ gitlab_runner_config_path }}'
    owner: root
    group: root
    mode: '0600'
  register: gitlab_runner_config
  no_log: '{{ gitlab_runner_nolog }}'

- name: Start GitLab runner container
  become: true
  community.docker.docker_container:
    name: '{{ gitlab_runner_container_name }}'
    hostname: gitlab-runner.{{ inventory_hostname }}
    image: '{{ gitlab_runner_image_full }}'
    pull: always
    restart_policy: always
    restart: '{{ gitlab_runner_config.changed }}'
    state: started
    memory_reservation: '{{ gitlab_runner_container_mem_res }}'
    memory: '{{ gitlab_runner_container_mem_lim }}'
    memory_swap: '{{ gitlab_runner_container_mem_swp }}'
    volumes:
      - '{{ gitlab_runner_config_dir }}:/etc/gitlab-runner'
      - /var/run/docker.sock:/var/run/docker.sock

- name: Verify GitLab runner container is running
  become: true
  community.docker.docker_container_info:
    name: '{{ gitlab_runner_container_name }}'
  register: gitlab_runner_container_info
  until:
    - gitlab_runner_container_info.exists
    - gitlab_runner_container_info.container.State.Running | bool
  retries: 20
  delay: 3
  when: not ansible_check_mode

- name: Verify GitLab runner
  become: true
  community.docker.docker_container_exec:
    container: '{{ gitlab_runner_container_name }}'
    argv:
      - gitlab-runner
      - verify
      - --delete
  changed_when: false
  no_log: '{{ gitlab_runner_nolog }}'
  when: not ansible_check_mode
