---

- name: Assert GitLab runner required variables are set
  ansible.builtin.assert:
    that:
      - gitlab_runner_mode in ['dedicated', 'docker']
      - gitlab_runner_token is not none
      - gitlab_runner_token | string | length > 0
      - gitlab_runner_url is not none
      - gitlab_runner_url | string | length > 0
      - gitlab_runner_executor is not none
      - gitlab_runner_executor | string | length > 0
      - gitlab_runner_docker_image_tag is not none
      - gitlab_runner_docker_image_tag | string | length > 0
    fail_msg: Define gitlab_runner_url, gitlab_runner_token, and a valid gitlab_runner_mode before running role gitlab_runner.
  no_log: '{{ gitlab_runner_nolog }}'

- name: Assert Docker GitLab runner variables are set
  ansible.builtin.assert:
    that:
      - gitlab_runner_image_tag is not none
      - gitlab_runner_image_tag | string | length > 0
    fail_msg: Define gitlab_runner_image_tag when gitlab_runner_mode is docker.
  no_log: '{{ gitlab_runner_nolog }}'
  when: gitlab_runner_mode == 'docker'
