---

runtime_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
runtime_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
runtime_nolog: '{{ (runtime_ci_mode | bool) and not (runtime_debug_mode | bool) }}'
runtime_pg_provision_enabled: "{{ runtime_pg_admin_user | string | length > 0 and runtime_pg_admin_pass | string | length > 0 }}"
runtime_pg_backup_s3_enabled: "{{ runtime_pg_backup_s3_access_key | string | length > 0 and runtime_pg_backup_s3_secret_key | string | length > 0 }}"
runtime_pg_recover_s3_enabled: "{{ runtime_pg_recover_s3_access_key | string | length > 0 and runtime_pg_recover_s3_secret_key | string | length > 0 }}"
runtime_selected_apps: "{{ runtime_apps | default([], true) | selectattr('enabled', 'undefined') | list + runtime_apps | default([], true) | selectattr('enabled', 'defined') | selectattr('enabled') | list }}"
runtime_pg_base_items: "{{ runtime_pg_bases | default([], true) }}"
runtime_pg_provision_items: "{{ runtime_pg_base_items | selectattr('provision', 'undefined') | list + runtime_pg_base_items | selectattr('provision', 'defined') | selectattr('provision') | list }}"
runtime_pg_provision_requested: "{{ runtime_pg_provision_items | length > 0 }}"
runtime_unit_secret_items: >-
  {%- set items = [] -%}
  {%- for app in runtime_selected_apps -%}
    {%- for env in app.envs | default([], true) -%}
      {%- for service in env.services | default([], true) if service.secrets is defined and service.secrets | length > 0 -%}
        {%- set _ = items.append({'app': app.name, 'env': env.slug, 'unit': service.name, 'secrets': service.secrets}) -%}
      {%- endfor -%}
    {%- endfor -%}
  {%- endfor -%}
  {{ items }}
