---

image: python:3.13-slim

stages:
  - check

variables:
  UV_CACHE_DIR: .uv-cache

cache:
  paths:
    - .uv-cache/
    - .ansible/

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ca-certificates curl git
  - pip install uv
  - uv sync
  - uv run ansible-galaxy collection install -r requirements.yml

check:
  stage: check
  script:
    - uv run pre-commit run --hook-stage pre-commit --all-files
    - uv run pytest tests/static tests/unit
    - uv run ansible-galaxy collection build
