---

base_hardening_user_process_persistence_enabled: false
base_hardening_ssh_port: 22
base_hardening_ssh_users: []
base_hardening_sysctl_config:
  - name: net.ipv4.conf.default.rp_filter
    value: '2'

  - name: net.ipv4.conf.all.rp_filter
    value: '2'

  - name: net.ipv4.conf.default.accept_redirects
    value: '0'

  - name: net.ipv4.conf.all.accept_redirects
    value: '0'

  - name: net.ipv4.conf.default.send_redirects
    value: '0'

  - name: net.ipv4.conf.all.send_redirects
    value: '0'

  - name: net.ipv4.icmp_echo_ignore_broadcasts
    value: '1'

  - name: net.ipv4.icmp_ignore_bogus_error_responses
    value: '1'

  - name: net.ipv4.tcp_syncookies
    value: '1'

  - name: kernel.randomize_va_space
    value: '2'

  - name: net.ipv4.ip_unprivileged_port_start
    value: '0'

  - name: vm.swappiness
    value: '20'

  - name: vm.max_map_count
    value: '524288'

  - name: fs.file-max
    value: '131072'
