---

iam_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
iam_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
iam_nolog: '{{ (iam_ci_mode | bool) and not (iam_debug_mode | bool) }}'
iam_provision_user:
  name: '{{ iam_provision_user_name }}'
  groups: '{{ iam_provision_user_groups }}'
  authorized_key_files: '{{ iam_provision_user_authorized_key_files }}'
  private_key_file: '{{ iam_provision_user_private_key_file }}'
  public_key_file: '{{ iam_provision_user_public_key_file }}'
  sudo_commands: '{{ iam_provision_user_sudo_commands }}'
iam_admin_user_names: "{{ iam_admin_users | map(attribute='name') | list }}"
iam_service_user_names: "{{ iam_service_users | map(attribute='name') | list }}"
iam_retained_user_names: >-
  {{ (iam_admin_user_names + [iam_provision_user_name] + iam_service_user_names + iam_cleanup_ignored_user_names) | unique | list }}
iam_master_password_hash: "{{ iam_master_pass | password_hash(hashtype='sha512', salt=iam_master_salt) }}"
