---

docker_nexus_image_name: sonatype/nexus3
docker_nexus_image_tag: ~
docker_nexus_image_full: '{{ docker_nexus_image_name }}:{{ docker_nexus_image_tag }}'
docker_nexus_http_port: 8081
docker_nexus_mem_res: 3000M
docker_nexus_mem_lim: 4000M
docker_nexus_mem_swp: 5000M
