---

- name: Create app stack docker overlay networks for each environment
  become: true
  community.docker.docker_network:
    name: '{{ item.0.name }}_{{ app_stack_cluster_realm }}_{{ item.1.slug }}'
    driver: overlay
    attachable: true
    state: present
  loop: "{{ app_stack_selected_apps | selectattr('envs', 'defined') | list | subelements('envs') }}"
  loop_control:
    label: '{{ item.0.name }}_{{ app_stack_cluster_realm }}_{{ item.1.slug }}'
  when: app_stack_network_enabled | bool
