---

- name: Validate app stack configuration
  ansible.builtin.include_tasks: validate.yml
  tags:
    - always

- name: Create app stack docker overlay networks for each environment
  become: true
  community.docker.docker_network:
    name: '{{ item.0.name }}_{{ app_stack_cluster_realm }}_{{ item.1.slug }}'
    driver: overlay
    attachable: true
    state: present
  loop: "{{ app_stack_selected_apps | selectattr('envs', 'defined') | list | subelements('envs') }}"
  loop_control:
    label: '{{ item.0.name }}_{{ app_stack_cluster_realm }}_{{ item.1.slug }}'
  when: app_stack_network_enabled | bool

- name: Create app stack PostgreSQL env directory
  become: true
  ansible.builtin.file:
    path: /home/{{ item.name }}/postgres
    state: directory
    mode: '0750'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
  loop: '{{ app_stack_selected_apps }}'
  loop_control:
    label: '{{ item.name }}'
  when: app_stack_enabled | bool

- name: Create app stack secret directory
  become: true
  ansible.builtin.file:
    path: /home/{{ item.name }}/secrets
    state: directory
    mode: '0750'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
  loop: '{{ app_stack_selected_apps }}'
  loop_control:
    label: '{{ item.name }}'
  when: app_stack_enabled | bool

- name: Create app stack secrets for each environment
  become: true
  vars:
    env_slug: '{{ item.0.slug }}'
    service_name: '{{ item.1.name }}'
    sec_realm: '{{ app_stack_realm_secrets | default({}, true) }}'
    sec_env: "{{ (((app_stack_secrets[app_stack_app_name] | default(app_stack_secrets, true))[env_slug] | default({}, true))[service_name] | default({}, true)) }}"
  ansible.builtin.copy:
    content: '{{ sec_realm | combine(sec_env) | to_nice_json }}'
    dest: '/home/{{ app_stack_app_name }}/secrets/{{ app_stack_cluster_realm }}_{{ env_slug }}_{{ service_name }}.json'
    mode: '0600'
    owner: '{{ app_stack_app_name }}'
    group: '{{ app_stack_app_name }}'
    backup: '{{ app_stack_secret_file_backup_mode | bool }}'
    force: '{{ app_stack_secret_file_force_mode | bool }}'
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).services | default([], true) | selectattr('secrets', 'defined') | selectattr('secrets', 'equalto', true) | list)) | list }}"
  loop_control:
    label: '{{ app_stack_app_name }}_{{ app_stack_cluster_realm }}_{{ env_slug }}_{{ service_name }}'
  when: app_stack_enabled | bool

- name: Create app stack PostgreSQL users for app user definitions
  vars:
    env_slug: '{{ item.0.slug }}'
    pg_user_item: '{{ item.1 }}'
    pg_name_prefix: "{{ app_stack_app_name ~ '_' ~ app_stack_cluster_realm ~ '_' ~ env_slug }}"
    pg_user: "{{ pg_user_item.name | default(pg_name_prefix ~ '_' ~ pg_user_item.name_suffix, true) }}"
    pg_pass: "{{ pg_user_item.pass | default('', true) }}"
  community.postgresql.postgresql_user:
    name: '{{ pg_user }}'
    password: "{{ pg_pass if pg_pass | string | length > 0 else omit }}"
    role_attr_flags: CREATEDB
    login_host: '{{ app_stack_pg_host }}'
    login_port: '{{ app_stack_pg_port }}'
    ssl_mode: '{{ app_stack_pg_sslmode }}'
    login_user: '{{ app_stack_pg_admin_user }}'
    login_password: '{{ app_stack_pg_admin_pass }}'
  run_once: true
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).pg_users | default([], true))) | list }}"
  loop_control:
    label: '{{ pg_user }}'
  when:
    - app_stack_enabled | bool
    - app_stack_pg_provision_enabled | bool

- name: Create app stack PostgreSQL databases for app database definitions
  vars:
    env_slug: '{{ item.0.slug }}'
    pg_base_item: '{{ item.1 }}'
    pg_name_prefix: "{{ app_stack_app_name ~ '_' ~ app_stack_cluster_realm ~ '_' ~ env_slug }}"
    pg_db_name: "{{ pg_base_item.name | default(pg_name_prefix ~ '_' ~ pg_base_item.name_suffix, true) }}"
    pg_owner: "{{ pg_base_item.owner | default(pg_name_prefix ~ '_' ~ pg_base_item.owner_suffix, true) }}"
  community.postgresql.postgresql_db:
    name: '{{ pg_db_name }}'
    owner: '{{ pg_owner }}'
    encoding: UTF-8
    template: template0
    login_host: '{{ app_stack_pg_host }}'
    login_port: '{{ app_stack_pg_port }}'
    ssl_mode: '{{ app_stack_pg_sslmode }}'
    login_user: '{{ app_stack_pg_admin_user }}'
    login_password: '{{ app_stack_pg_admin_pass }}'
  run_once: true
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).pg_bases | default([], true))) | list }}"
  loop_control:
    label: '{{ pg_db_name }}'
  when:
    - app_stack_enabled | bool
    - app_stack_pg_provision_enabled | bool

- name: Create app stack PostgreSQL users for services
  vars:
    env_slug: '{{ item.0.slug }}'
    service_name: '{{ item.1.name }}'
    pg_env_overrides: "{{ item.1.postgres.envs | default({}, true) | dict2items | selectattr('key', 'equalto', env_slug) | map(attribute='value') | first | default({}, true) }}"
    pg_name_prefix: "{{ app_stack_app_name ~ '_' ~ app_stack_cluster_realm ~ '_' ~ env_slug }}"
    pg_user_suffix: "{{ pg_env_overrides.user_suffix | default(item.1.postgres.user_suffix | default(service_name, true), true) }}"
    pg_user: "{{ pg_env_overrides.user_name | default(item.1.postgres.user_name | default(pg_name_prefix ~ '_' ~ pg_user_suffix, true), true) }}"
    pg_service_secrets: "{{ (((app_stack_secrets[app_stack_app_name] | default({}, true))[env_slug] | default({}, true))[service_name] | default({}, true)) }}"
    pg_pass: "{{ pg_env_overrides.pass | default(item.1.postgres.pass | default(pg_service_secrets.pg_pass | default(pg_service_secrets.PG_PASS | default('', true), true), true), true) }}"
  community.postgresql.postgresql_user:
    name: '{{ pg_user }}'
    password: '{{ pg_pass }}'
    role_attr_flags: CREATEDB
    login_host: '{{ app_stack_pg_host }}'
    login_port: '{{ app_stack_pg_port }}'
    ssl_mode: '{{ app_stack_pg_sslmode }}'
    login_user: '{{ app_stack_pg_admin_user }}'
    login_password: '{{ app_stack_pg_admin_pass }}'
  run_once: true
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).services | default([], true) | selectattr('postgres', 'defined') | list)) | list }}"
  loop_control:
    label: '{{ pg_user }}'
  when:
    - app_stack_enabled | bool
    - app_stack_pg_provision_enabled | bool
    - ((app_stack_selected_apps | first | default({})).pg_users | default([], true) | length) == 0

- name: Create app stack PostgreSQL databases for services
  vars:
    env_slug: '{{ item.0.slug }}'
    service_name: '{{ item.1.name }}'
    pg_env_overrides: "{{ item.1.postgres.envs | default({}, true) | dict2items | selectattr('key', 'equalto', env_slug) | map(attribute='value') | first | default({}, true) }}"
    pg_name_prefix: "{{ app_stack_app_name ~ '_' ~ app_stack_cluster_realm ~ '_' ~ env_slug }}"
    pg_user_suffix: "{{ pg_env_overrides.user_suffix | default(item.1.postgres.user_suffix | default(service_name, true), true) }}"
    pg_base_suffix: "{{ pg_env_overrides.base_suffix | default(item.1.postgres.base_suffix | default(service_name, true), true) }}"
    pg_db_name: "{{ pg_env_overrides.base_name | default(item.1.postgres.base_name | default(pg_name_prefix ~ '_' ~ pg_base_suffix, true), true) }}"
    pg_owner: "{{ pg_env_overrides.user_name | default(item.1.postgres.user_name | default(pg_name_prefix ~ '_' ~ pg_user_suffix, true), true) }}"
  community.postgresql.postgresql_db:
    name: '{{ pg_db_name }}'
    owner: '{{ pg_owner }}'
    encoding: UTF-8
    template: template0
    login_host: '{{ app_stack_pg_host }}'
    login_port: '{{ app_stack_pg_port }}'
    ssl_mode: '{{ app_stack_pg_sslmode }}'
    login_user: '{{ app_stack_pg_admin_user }}'
    login_password: '{{ app_stack_pg_admin_pass }}'
  run_once: true
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).services | default([], true) | selectattr('postgres', 'defined') | list)) | list }}"
  loop_control:
    label: '{{ pg_db_name }}'
  when:
    - app_stack_enabled | bool
    - app_stack_pg_provision_enabled | bool
    - (app_stack_selected_apps | first | default({})).pg_bases | default([], true) | length == 0

- name: Create app stack service PostgreSQL env files
  become: true
  vars:
    env_slug: '{{ item.0.slug }}'
    service_name: '{{ item.1.name }}'
    pg_env_overrides: "{{ item.1.postgres.envs | default({}, true) | dict2items | selectattr('key', 'equalto', env_slug) | map(attribute='value') | first | default({}, true) }}"
    pg_name_prefix: "{{ app_stack_app_name ~ '_' ~ app_stack_cluster_realm ~ '_' ~ env_slug }}"
    pg_user_suffix: "{{ pg_env_overrides.user_suffix | default(item.1.postgres.user_suffix | default(service_name, true), true) }}"
    pg_base_suffix: "{{ pg_env_overrides.base_suffix | default(item.1.postgres.base_suffix | default(service_name, true), true) }}"
    pg_user: "{{ pg_env_overrides.user_name | default(item.1.postgres.user_name | default(pg_name_prefix ~ '_' ~ pg_user_suffix, true), true) }}"
    pg_base: "{{ pg_env_overrides.base_name | default(item.1.postgres.base_name | default(pg_name_prefix ~ '_' ~ pg_base_suffix, true), true) }}"
    pg_recover_s3_prefix_template: "{{ pg_env_overrides.recover_s3_prefix_template | default(item.1.postgres.recover_s3_prefix_template | default(app_stack_pg_recover_s3_prefix_template, true), true) }}"
    pg_service_secrets: "{{ (((app_stack_secrets[app_stack_app_name] | default({}, true))[env_slug] | default({}, true))[service_name] | default({}, true)) }}"
    pg_pass: "{{ pg_env_overrides.pass | default(item.1.postgres.pass | default(pg_service_secrets.pg_pass | default(pg_service_secrets.PG_PASS | default('', true), true), true), true) }}"
    pg_host: '{{ app_stack_pg_host }}'
    pg_port: '{{ app_stack_pg_port }}'
  ansible.builtin.template:
    src: pg.env.j2
    dest: '/home/{{ app_stack_app_name }}/postgres/{{ pg_base }}.env'
    mode: '0600'
    owner: '{{ app_stack_app_name }}'
    group: '{{ app_stack_app_name }}'
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).services | default([], true) | selectattr('postgres', 'defined') | list)) | list }}"
  loop_control:
    label: '{{ pg_base }}'
  when:
    - app_stack_enabled | bool
    - pg_base_suffix == service_name or pg_env_overrides.base_name is defined or item.1.postgres.base_name is defined

- name: Create app stack admin PostgreSQL client env file
  become: true
  vars:
    pg_host: '{{ app_stack_pg_host }}'
    pg_port: '{{ app_stack_pg_port }}'
    pg_user: '{{ app_stack_pg_admin_user }}'
    pg_pass: '{{ app_stack_pg_admin_pass }}'
    pg_base: postgres
  ansible.builtin.template:
    src: postgres.env.j2
    dest: /home/{{ app_stack_app_name }}/postgres/postgres.env
    mode: '0600'
    owner: '{{ app_stack_app_name }}'
    group: '{{ app_stack_app_name }}'
  no_log: '{{ app_stack_nolog }}'
  when:
    - app_stack_enabled | bool
    - app_stack_pg_provision_enabled | bool

- name: Create app stack extra PostgreSQL client env files
  become: true
  vars:
    pg_base: '{{ item.pg_base }}'
    pg_user: '{{ item.pg_user }}'
    pg_pass: '{{ item.pg_pass }}'
    pg_host: "{{ item.pg_host | default(app_stack_pg_host, true) }}"
    pg_port: "{{ item.pg_port | default(app_stack_pg_port, true) }}"
    pg_sslmode: "{{ item.pg_sslmode | default(app_stack_pg_sslmode, true) }}"
    pg_recover_s3_prefix_template: "{{ item.recover_s3_prefix_template | default(app_stack_pg_recover_s3_prefix_template, true) }}"
  ansible.builtin.template:
    src: pg.env.j2
    dest: /home/{{ app_stack_app_name }}/postgres/{{ pg_base }}.env
    mode: '0600'
    owner: '{{ app_stack_app_name }}'
    group: '{{ app_stack_app_name }}'
  no_log: '{{ app_stack_nolog }}'
  loop: '{{ app_stack_extra_pg_envs }}'
  loop_control:
    label: "{{ item.pg_base | default('<missing-base>', true) }}"
  when:
    - app_stack_enabled | bool
    - item.enabled | default(true, true) | bool

- name: Create app stack shell shortcuts
  become: true
  ansible.builtin.template:
    src: bash_local.j2
    dest: '/home/{{ app_stack_backup_app.name }}/.bash_local'
    mode: '0640'
    owner: '{{ app_stack_backup_app.name }}'
    group: '{{ app_stack_backup_app.name }}'
  loop: '{{ app_stack_selected_apps }}'
  loop_control:
    label: '{{ app_stack_backup_app.name }}'
  vars:
    app_stack_backup_app: '{{ item }}'
  when:
    - app_stack_enabled | bool

- name: Create app stack PostgreSQL backup sudoers rule
  become: true
  ansible.builtin.template:
    src: postgres_backup_sudoers.j2
    dest: "{{ app_stack_postgres_backup_sudoers_path | default('/etc/sudoers.d/' ~ app_stack_app_name ~ '-postgres-backup', true) }}"
    mode: '0440'
    owner: root
    group: root
    validate: /usr/sbin/visudo -cf %s
  when:
    - app_stack_enabled | bool
    - app_stack_pg_backup_s3_enabled | bool or app_stack_pg_recover_s3_enabled | bool
    - app_stack_postgres_backup_sudoers_enabled | bool
