---

- name: Validate app stack configuration
  ansible.builtin.include_tasks: validate.yml
  tags:
    - always

- name: Configure app stack Docker resources
  ansible.builtin.include_tasks: docker.yml

- name: Configure app stack secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Configure app stack PostgreSQL resources
  ansible.builtin.include_tasks: postgres.yml
