---

- name: Create app stack secret directory
  become: true
  ansible.builtin.file:
    path: /home/{{ item.name }}/secrets
    state: directory
    mode: '0750'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
  loop: '{{ app_stack_selected_apps }}'
  loop_control:
    label: '{{ item.name }}'
  when: app_stack_enabled | bool

- name: Create app stack secrets for each environment
  become: true
  vars:
    env_slug: '{{ item.0.slug }}'
    service_name: '{{ item.1.name }}'
    sec_realm: '{{ app_stack_realm_secrets | default({}, true) }}'
    sec_env: "{{ (((app_stack_secrets[app_stack_app_name] | default(app_stack_secrets, true))[env_slug] | default({}, true))[service_name] | default({}, true)) }}"
  ansible.builtin.copy:
    content: '{{ sec_realm | combine(sec_env) | to_nice_json }}'
    dest: '/home/{{ app_stack_app_name }}/secrets/{{ app_stack_cluster_realm }}_{{ env_slug }}_{{ service_name }}.json'
    mode: '0600'
    owner: '{{ app_stack_app_name }}'
    group: '{{ app_stack_app_name }}'
    backup: '{{ app_stack_secret_file_backup_mode | bool }}'
    force: '{{ app_stack_secret_file_force_mode | bool }}'
  no_log: '{{ app_stack_nolog }}'
  loop: "{{ ((app_stack_selected_apps | first | default({})).envs | default([], true)) | product(((app_stack_selected_apps | first | default({})).services | default([], true) | selectattr('secrets', 'defined') | selectattr('secrets', 'equalto', true) | list)) | list }}"
  loop_control:
    label: '{{ app_stack_app_name }}_{{ app_stack_cluster_realm }}_{{ env_slug }}_{{ service_name }}'
  when: app_stack_enabled | bool
