---

- name: Assert Docker image tag variables are set
  ansible.builtin.assert:
    that:
      - docker_mailpit_image_tag is not none
      - docker_mailpit_image_tag | string | length > 0
    fail_msg: Define non-empty Docker image tag variables before running role docker_mailpit.
