---

docker_daemon_base_config:
  log-driver: json-file
  log-opts:
    max-size: 10m
    max-file: '5'
docker_daemon_mirror_config: "{{ (docker_mirrors | length > 0) | ternary({'registry-mirrors': docker_mirrors}, {}) }}"
docker_daemon_config: '{{ docker_daemon_base_config | combine(docker_daemon_mirror_config) }}'
docker_restart_approved: >-
  {{ docker_yes_mode or (docker_restart_approval is defined and (docker_restart_approval.user_input | default('') | lower) == 'yes') }}
