---

docker_daemon_base_config:
  log-driver: json-file
  log-opts:
    max-size: 10m
    max-file: '5'
  registry-mirrors: '{{ docker_mirrors }}'
docker_daemon_tcp_config:
  hosts:
    - unix:///var/run/docker.sock
    - tcp://{{ docker_tcp_socket_bind_address }}:{{ docker_tcp_socket_port }}
docker_daemon_config: "{{ docker_daemon_base_config | combine((docker_tcp_socket_enabled | bool) | ternary(docker_daemon_tcp_config, {})) }}"
