---

docker_prometheus_cluster_platform: ~
docker_prometheus_cluster_realm: ~
docker_prometheus_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
docker_prometheus_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
docker_prometheus_nolog: '{{ (docker_prometheus_ci_mode | bool) and not (docker_prometheus_debug_mode | bool) }}'
docker_prometheus_alertmanager_host: 127.0.0.1
docker_prometheus_alertmanager_http_port: 9093
docker_prometheus_config_content: ''
docker_prometheus_config_template: prometheus.yml.j2
docker_prometheus_custom_alerts: ''
docker_prometheus_fqdn_ext: ~
docker_prometheus_http_port: 9090
docker_prometheus_image_name: prom/prometheus
docker_prometheus_image_tag: v3.11.3
docker_prometheus_image_full: '{{ docker_prometheus_image_name }}:{{ docker_prometheus_image_tag }}'
docker_prometheus_promtool_image_name: dnanexus/promtool
docker_prometheus_promtool_image_tag: 2.9.2
docker_prometheus_promtool_image_full: '{{ docker_prometheus_promtool_image_name }}:{{ docker_prometheus_promtool_image_tag }}'
docker_prometheus_blackbox_image_name: prom/blackbox-exporter
docker_prometheus_blackbox_image_tag: v0.28.0
docker_prometheus_blackbox_image_full: '{{ docker_prometheus_blackbox_image_name }}:{{ docker_prometheus_blackbox_image_tag }}'
docker_prometheus_blackbox_config_content: ''
docker_prometheus_loki_host: 127.0.0.1
docker_prometheus_loki_http_port: 3100
docker_prometheus_mem_res: 1000M
docker_prometheus_mem_lim: 1500M
docker_prometheus_mem_swp: 2000M
docker_prometheus_blackbox_mem_res: 100M
docker_prometheus_blackbox_mem_lim: 150M
docker_prometheus_blackbox_mem_swp: 200M
docker_prometheus_rules_content: ''
docker_prometheus_rules_template: alerts.yml.j2
docker_prometheus_targets: []
docker_prometheus_web_external_url: ''
docker_prometheus_extra_args: []
