---

- name: Create host directories
  become: true
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /opt/postgres
    - /opt/postgres/config
    - /opt/postgres/bin

- name: Create PostgreSQL log directory
  become: true
  ansible.builtin.file:
    path: /opt/postgres/log
    state: directory
    mode: '0755'
    owner: '{{ docker_postgres_os_user_uid }}'
    group: '{{ docker_postgres_os_user_gid }}'

- name: Install PostgreSQL config
  become: true
  ansible.builtin.template:
    src: postgresql.{{ docker_postgres_mode }}.conf.j2
    dest: /opt/postgres/config/postgresql.conf
    mode: '0644'
    owner: root
    group: root
  no_log: '{{ docker_postgres_nolog }}'

- name: Install templated PostgreSQL configs
  become: true
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: /opt/postgres/config/{{ item.dest }}
    mode: '0644'
    owner: root
    group: root
  loop:
    - src: pg_hba.conf.j2
      dest: pg_hba.conf

- name: Install PostgreSQL dotenv
  become: true
  ansible.builtin.template:
    src: postgres.env.j2
    dest: /opt/postgres/env
    mode: '0600'
    owner: root
    group: root
  no_log: '{{ docker_postgres_nolog }}'

- name: Make sure PostgreSQL log files are writable by PostgreSQL
  become: true
  ansible.builtin.file:
    path: /opt/postgres/log/{{ item }}
    state: touch
    mode: '0644'
    owner: '{{ docker_postgres_os_user_uid }}'
    group: '{{ docker_postgres_os_user_gid }}'
    access_time: preserve
    modification_time: preserve
  loop: "{{ ['psql_history'] + (['walg_archive.log'] if docker_postgres_walg_backup_enabled | bool else []) }}"

- name: Create Docker volume
  become: true
  community.docker.docker_volume:
    name: '{{ docker_postgres_data_volume }}'
