---

- name: Install PostgreSQL WAL-G executables
  become: true
  ansible.builtin.copy:
    src: scripts/{{ item }}.sh
    dest: /opt/postgres/bin/{{ item }}
    mode: '0755'
    owner: root
    group: root
  loop:
    - snap_dump
    - snap_restore
    - walg_backup
    - walg_recover

- name: Create PostgreSQL WAL-G image build directory
  become: true
  ansible.builtin.file:
    path: /opt/postgres/walg
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Install PostgreSQL WAL-G Dockerfile
  become: true
  ansible.builtin.copy:
    src: docker/Dockerfile
    dest: /opt/postgres/walg/Dockerfile
    mode: '0644'
    owner: root
    group: root

- name: Build custom PostgreSQL image with WAL-G support
  community.docker.docker_image:
    name: '{{ docker_postgres_image_name }}-walg'
    tag: '{{ docker_postgres_image_tag }}'
    source: build
    force_source: true
    build:
      path: /opt/postgres/walg
      dockerfile: Dockerfile
      args:
        POSTGRES_IMAGE: '{{ docker_postgres_image_full }}'
        WALG_BINARY_URL: '{{ docker_postgres_walg_binary_url }}'

- name: Start PostgreSQL WAL-G container
  community.docker.docker_container:
    hostname: postgres.{{ inventory_hostname }}
    name: '{{ docker_postgres_container }}'
    image: '{{ docker_postgres_image_runtime }}'
    pull: false
    env:
      POSTGRES_USER: '{{ docker_postgres_pg_admin_user }}'
      POSTGRES_PASSWORD: '{{ docker_postgres_pg_admin_pass }}'
      PGDATA: '{{ docker_postgres_data_dir }}'
      PGDATABASE: postgres
      PGUSER: '{{ docker_postgres_pg_admin_user }}'
      PGHOST: /var/run/postgresql
      PGPORT: '{{ docker_postgres_port | string }}'
      WALG_COMPRESSION_METHOD: brotli
      WALG_COMPRESSION_LEVEL: '5'
      WALG_S3_PREFIX: >-
        {{
          ('s3://' ~ docker_postgres_walg_backup_s3_bucket ~ '/' ~ docker_postgres_walg_backup_s3_prefix)
          if docker_postgres_walg_backup_s3_access_key | string | length > 0
          and docker_postgres_walg_backup_s3_secret_key | string | length > 0
          else ''
        }}
      AWS_ENDPOINT: '{{ docker_postgres_walg_backup_s3_endpoint }}'
      AWS_REGION: '{{ docker_postgres_walg_backup_s3_region }}'
      AWS_ACCESS_KEY_ID: '{{ docker_postgres_walg_backup_s3_access_key }}'
      AWS_SECRET_ACCESS_KEY: '{{ docker_postgres_walg_backup_s3_secret_key }}'
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart_policy: unless-stopped
    shm_size: '{{ ((docker_postgres_mem_lim[:-1] | int) * 0.3) | int }}M'
    memory_reservation: '{{ docker_postgres_mem_res }}'
    memory: '{{ docker_postgres_mem_lim }}'
    memory_swap: '{{ docker_postgres_mem_swp }}'
    network_mode: host
    volumes:
      - /opt/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /opt/postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
      - /opt/postgres/config:/opt/config:ro
      - /opt/postgres/log:/var/log/postgresql
      - /opt/postgres/psql_history:/var/lib/postgresql/.psql_history
      - '{{ docker_postgres_data_volume }}:{{ docker_postgres_data_root }}'
    healthcheck:
      test: [CMD, pg_isready]
      timeout: 3s
      interval: 30s
      start_period: 30s
  no_log: '{{ docker_postgres_nolog }}'
