---

- name: Start vanilla PostgreSQL container
  community.docker.docker_container:
    hostname: postgres.{{ inventory_hostname }}
    name: '{{ docker_postgres_container }}'
    image: '{{ docker_postgres_image_full }}'
    pull: false
    env:
      POSTGRES_USER: '{{ docker_postgres_pg_admin_user }}'
      POSTGRES_PASSWORD: '{{ docker_postgres_pg_admin_pass }}'
      PGDATA: '{{ docker_postgres_data_dir }}'
      PGDATABASE: postgres
      PGUSER: '{{ docker_postgres_pg_admin_user }}'
      PGHOST: /var/run/postgresql
      PGPORT: '{{ docker_postgres_port | string }}'
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    restart_policy: unless-stopped
    shm_size: '{{ ((docker_postgres_mem_lim[:-1] | int) * 0.3) | int }}M'
    memory_reservation: '{{ docker_postgres_mem_res }}'
    memory: '{{ docker_postgres_mem_lim }}'
    memory_swap: '{{ docker_postgres_mem_swp }}'
    network_mode: host
    volumes:
      - /opt/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /opt/postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
      - /opt/postgres/config:/opt/config:ro
      - /opt/postgres/log:/var/log/postgresql
      - /opt/postgres/psql_history:/var/lib/postgresql/.psql_history
      - '{{ docker_postgres_data_volume }}:{{ docker_postgres_data_root }}'
    healthcheck:
      test: [CMD, pg_isready]
      timeout: 3s
      interval: 30s
      start_period: 30s
  no_log: '{{ docker_postgres_nolog }}'
