---

- name: Install walg wrapper
  become: true
  ansible.builtin.template:
    src: config/walg.sh.j2
    dest: /opt/postgres/config/walg.sh
    mode: '0755'
    owner: root
    group: root
  no_log: '{{ docker_postgres_nolog }}'
