---

- name: Prepare PostgreSQL WAL-G tools
  ansible.builtin.include_tasks: setup_walg_tools.yml
  when: docker_postgres_walg_image_info is not defined

- name: Start PostgreSQL WAL-G container
  become: true
  community.docker.docker_container:
    hostname: postgres.{{ inventory_hostname }}
    name: '{{ docker_postgres_container }}'
    image: '{{ docker_postgres_image_runtime }}'
    pull: false
    env:
      POSTGRES_USER: '{{ docker_postgres_pg_admin_user }}'
      POSTGRES_PASSWORD: '{{ docker_postgres_pg_admin_pass }}'
      PGDATA: '{{ docker_postgres_data_dir }}'
      PGDATABASE: postgres
      PGUSER: '{{ docker_postgres_pg_admin_user }}'
      PGHOST: /var/run/postgresql
      PGPORT: '{{ docker_postgres_port | string }}'
      WALG_COMPRESSION_METHOD: '{{ docker_postgres_walg_backup_compression_method }}'
      WALG_COMPRESSION_LEVEL: '{{ docker_postgres_walg_backup_compression_level | string }}'
      WALG_S3_PREFIX: "{{ docker_postgres_walg_backup_storage_path if docker_postgres_walg_backup_s3_enabled | bool else '' }}"
      WALG_FILE_PREFIX: "{{ docker_postgres_walg_backup_storage_path if docker_postgres_walg_backup_local_enabled | bool else '' }}"
      AWS_ENDPOINT: "{{ docker_postgres_walg_backup_s3_endpoint if docker_postgres_walg_backup_s3_enabled | bool else '' }}"
      AWS_REGION: "{{ docker_postgres_walg_backup_s3_region if docker_postgres_walg_backup_s3_enabled | bool else '' }}"
      AWS_ACCESS_KEY_ID: "{{ docker_postgres_walg_backup_s3_access_key if docker_postgres_walg_backup_s3_enabled | bool else '' }}"
      AWS_SECRET_ACCESS_KEY: "{{ docker_postgres_walg_backup_s3_secret_key if docker_postgres_walg_backup_s3_enabled | bool else '' }}"
    command: postgres -c 'config_file=/opt/config/postgresql.conf'
    restart_policy: unless-stopped
    shm_size: '{{ ((docker_postgres_mem_lim[:-1] | int) * 0.3) | int }}M'
    memory_reservation: '{{ docker_postgres_mem_res }}'
    memory: '{{ docker_postgres_mem_lim }}'
    memory_swap: '{{ docker_postgres_mem_swp }}'
    network_mode: host
    volumes: '{{ docker_postgres_walg_container_volumes }}'
    healthcheck:
      test: [CMD, pg_isready]
      timeout: 3s
      interval: 30s
      start_period: 30s
  when: docker_postgres_walg_image_info.images | length > 0 or not ansible_check_mode
  no_log: '{{ docker_postgres_nolog }}'
