---

- name: Verify PostgreSQL container is running
  become: true
  community.docker.docker_container_info:
    name: '{{ docker_postgres_container }}'
  register: docker_postgres_container_info
  until:
    - docker_postgres_container_info.exists
    - docker_postgres_container_info.container.State.Running | bool
  retries: 20
  delay: 3
  when: not ansible_check_mode

- name: Wait for PostgreSQL to be ready
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: '{{ docker_postgres_port }}'
    sleep: 3
    timeout: 60
    state: started
  when: not ansible_check_mode

- name: Reload PostgreSQL config
  become: true
  ansible.builtin.command: docker exec {{ docker_postgres_container }} psql -p {{ docker_postgres_port }} -U {{ docker_postgres_pg_admin_user }} -c "SELECT pg_reload_conf()"
  changed_when: false
  when: not ansible_check_mode
