---

- name: Validate Docker Engine events exporter variable contract
  ansible.builtin.include_tasks: validate.yml

- name: Start Docker Engine events exporter container
  become: true
  community.docker.docker_container:
    hostname: '{{ docker_engine_events_exporter_container_name }}.{{ inventory_hostname }}'
    name: '{{ docker_engine_events_exporter_container_name }}'
    image: '{{ docker_engine_events_exporter_image_full }}'
    env:
      DOCKER_HOSTNAME: '{{ docker_engine_events_exporter_hostname }}'
    restart_policy: unless-stopped
    memory_reservation: '{{ docker_engine_events_exporter_mem_res }}'
    memory: '{{ docker_engine_events_exporter_mem_lim }}'
    memory_swap: '{{ docker_engine_events_exporter_mem_swp }}'
    ports:
      - 127.0.0.1:{{ docker_engine_events_exporter_http_port }}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

- name: Verify Docker Engine events exporter container is running
  become: true
  community.docker.docker_container_info:
    name: '{{ docker_engine_events_exporter_container_name }}'
  register: docker_engine_events_exporter_container_info
  until:
    - docker_engine_events_exporter_container_info.exists
    - docker_engine_events_exporter_container_info.container.State.Running | bool
  retries: 10
  delay: 1
  when: not ansible_check_mode

- name: Wait for Docker Engine events exporter to be ready
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: '{{ docker_engine_events_exporter_http_port }}'
    delay: 1
    timeout: 10
  when: not ansible_check_mode
