---

sentry_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
sentry_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
sentry_nolog: '{{ (sentry_ci_mode | bool) and not (sentry_debug_mode | bool) }}'

sentry_repo_url: https://github.com/getsentry/self-hosted.git
sentry_version: 26.3.1
sentry_install_dir: /opt/sentry
sentry_install_parent_dir: /opt

sentry_compose_profiles: errors-only
sentry_event_retention_days: 30
sentry_taskworker_concurrency: 3
sentry_report_self_hosted_issues: true

sentry_smtp_backend: smtp
sentry_smtp_host: ~
sentry_smtp_port: ~
sentry_smtp_user: ~
sentry_smtp_pass: ~
sentry_smtp_use_tls: false
sentry_smtp_use_ssl: true

sentry_web_host: 0.0.0.0
sentry_web_port: 9000
sentry_csrf_trusted_origins: []
