---

backups_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
backups_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
backups_nolog: '{{ (backups_ci_mode | bool) and not (backups_debug_mode | bool) }}'
backups_postgres_backup_s3_enabled: "{{ backups_postgres_backup_s3_access_key | string | length > 0 and backups_postgres_backup_s3_secret_key | string | length > 0 }}"
backups_postgres_recover_s3_enabled: "{{ backups_postgres_recover_s3_access_key | string | length > 0 and backups_postgres_recover_s3_secret_key | string | length > 0 }}"
backups_postgres_database_items: "{{ backups_postgres_databases | default([], true) | rejectattr('backup', 'defined') | list + backups_postgres_databases | default([], true) | selectattr('backup', 'defined') | selectattr('backup') | list }}"
