---

docker_sonarqube_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
docker_sonarqube_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
docker_sonarqube_nolog: '{{ (docker_sonarqube_ci_mode | bool) and not (docker_sonarqube_debug_mode | bool) }}'
docker_sonarqube_image_name: sonarqube
docker_sonarqube_image_tag: 25.10.0.114319-community
docker_sonarqube_image_full: '{{ docker_sonarqube_image_name }}:{{ docker_sonarqube_image_tag }}'
docker_sonarqube_postgres_image_name: postgres
docker_sonarqube_postgres_image_tag: 17-alpine
docker_sonarqube_postgres_image_full: '{{ docker_sonarqube_postgres_image_name }}:{{ docker_sonarqube_postgres_image_tag }}'
docker_sonarqube_port: 9000
docker_sonarqube_postgres_user: sonar
docker_sonarqube_postgres_pass: ~
docker_sonarqube_postgres_database: sonar

docker_sonarqube_postgres_mem_res: 500M
docker_sonarqube_postgres_mem_lim: 750M
docker_sonarqube_postgres_mem_swp: 1000M
docker_sonarqube_mem_res: 1000M
docker_sonarqube_mem_lim: 1500M
docker_sonarqube_mem_swp: 2000M
