---

iam_admin_group: wheel
iam_cleanup_mode: true
iam_interactive_mode: "{{ lookup('env', 'INTERACTIVE') | default('1', true) | lower not in ['0', 'false'] }}"
iam_master_pass: ''
iam_master_salt: ''

iam_admin_users: []
iam_service_users: []
