---

iam_admin_group: wheel
iam_admin_linger_enabled: false
iam_cleanup_mode: true
iam_interactive_mode: "{{ lookup('env', 'INTERACTIVE') | default('1', true) | lower not in ['0', 'false'] }}"
iam_master_pass: ~
iam_master_salt: ~
iam_provision_user_name: iac
iam_provision_user_groups: []
iam_provision_user_authorized_key_files: []
iam_provision_user_private_key_file: ~
iam_provision_user_public_key_file: ~
iam_provision_user_sudo_commands:
  - ALL

iam_admin_users: []
iam_service_users: []
