---

- name: Validate Docker Swarm Zitadel inputs
  ansible.builtin.include_tasks: validate.yml

- name: Configure Zitadel PostgreSQL resources
  ansible.builtin.include_tasks: postgresql.yml
  when:
    - docker_swarm_zitadel_enabled | bool
    - docker_swarm_zitadel_pg_provision_enabled | bool

- name: Setup Zitadel swarm service
  ansible.builtin.include_tasks: setup.yml
  when: docker_swarm_zitadel_enabled | bool
