---

app_stack_enabled: false
app_stack_network_enabled: false
app_stack_app_name: ~
app_stack_apps: []
app_stack_cluster_realm: ~
app_stack_pg_admin_user: ''
app_stack_pg_admin_pass: ''
app_stack_pg_image: postgres:14-alpine
app_stack_pg_host: ~
app_stack_pg_port: 5432
app_stack_pg_sslmode: disable
app_stack_pg_restore_concurrency: 1
app_stack_pg_restore_no_prepare: false
app_stack_pg_restore_no_recreate: false
app_stack_secrets: {}
app_stack_realm_secrets: {}
app_stack_backups_secret: ''
app_stack_backups_s3_endpoint: ''
app_stack_backups_s3_region: ''
app_stack_backups_s3_bucket: ''
app_stack_backups_s3_access_key: ''
app_stack_backups_s3_secret_key: ''
app_stack_extra_pg_envs: []
app_stack_postgres_backup_sudoers_enabled: false
app_stack_postgres_backup_sudoers_path: ''
