---

- name: Create runtime docker overlay networks for each environment
  become: true
  community.docker.docker_network:
    name: '{{ item.0.name }}_{{ runtime_cluster_realm }}_{{ item.1.slug }}'
    driver: overlay
    attachable: true
    state: present
  loop: "{{ runtime_selected_apps | selectattr('envs', 'defined') | list | subelements('envs') }}"
  loop_control:
    label: '{{ item.0.name }}_{{ runtime_cluster_realm }}_{{ item.1.slug }}'
  when: runtime_network_enabled | bool

- name: Manage runtime unit Docker secrets
  ansible.builtin.include_tasks: secrets.yml
  loop: '{{ runtime_unit_secret_items }}'
  loop_control:
    label: '{{ item.app }}-{{ runtime_cluster_realm }}-{{ item.env }}-{{ item.unit }}'
  when:
    - runtime_enabled | bool
    - runtime_unit_secret_items | length > 0
