---

- name: Manage runtime unit Docker secret
  vars:
    runtime_unit_secret_prefix: '{{ item.app }}-{{ runtime_cluster_realm }}-{{ item.env }}-{{ item.unit }}'
    runtime_unit_secret_persistent_dotenv_path: '/home/{{ item.app }}/secrets/{{ runtime_cluster_realm }}_{{ item.env }}_{{ item.unit }}.env'
    runtime_unit_secret_dotenv_path: "{{ runtime_unit_secret_persistent_dotenv_path if runtime_secrets_dotenv | bool else runtime_unit_secret_temp_dotenv.path }}"
  block:
    - name: Create temporary runtime unit secret dotenv file
      become: true
      ansible.builtin.tempfile:
        state: file
        suffix: .env
      register: runtime_unit_secret_temp_dotenv
      check_mode: false
      changed_when: false
      when: not runtime_secrets_dotenv | bool

    - name: Render temporary runtime unit secret dotenv file
      become: true
      ansible.builtin.template:
        src: runtime_secret.env.j2
        dest: '{{ runtime_unit_secret_temp_dotenv.path }}'
        mode: '0600'
        owner: root
        group: root
      check_mode: false
      changed_when: false
      no_log: '{{ runtime_nolog }}'
      when: not runtime_secrets_dotenv | bool

    - name: Create runtime unit secret dotenv directory
      become: true
      ansible.builtin.file:
        path: '/home/{{ item.app }}/secrets'
        state: directory
        mode: '0750'
        owner: '{{ item.app }}'
        group: '{{ item.app }}'
      when: runtime_secrets_dotenv | bool

    - name: Render runtime unit secret dotenv file
      become: true
      ansible.builtin.template:
        src: runtime_secret.env.j2
        dest: '{{ runtime_unit_secret_persistent_dotenv_path }}'
        force: false
        mode: '0600'
        owner: '{{ item.app }}'
        group: '{{ item.app }}'
      no_log: '{{ runtime_nolog }}'
      when: runtime_secrets_dotenv | bool

    - name: Check runtime unit secret persistent dotenv file
      become: true
      ansible.builtin.stat:
        path: '{{ runtime_unit_secret_persistent_dotenv_path }}'
      register: runtime_unit_secret_persistent_dotenv
      changed_when: false
      when: runtime_secrets_dotenv | bool

    - name: Upsert runtime unit Docker secret
      become: true
      ansible.builtin.command:
        argv: "{{ [runtime_docker_secret_manager_path, 'upsert', '--prefix', runtime_unit_secret_prefix, '--file', runtime_unit_secret_dotenv_path] + (ansible_check_mode | ternary(['--check'], [])) }}"
      register: runtime_unit_secret_manager_result
      check_mode: false
      changed_when: "'status=created' in runtime_unit_secret_manager_result.stdout or 'status=would-create' in runtime_unit_secret_manager_result.stdout"
      no_log: '{{ runtime_nolog }}'
      when: not runtime_secrets_dotenv | bool or runtime_unit_secret_persistent_dotenv.stat.exists
  always:
    - name: Remove temporary runtime unit secret dotenv file
      become: true
      ansible.builtin.file:
        path: '{{ runtime_unit_secret_temp_dotenv.path }}'
        state: absent
      changed_when: false
      when: runtime_unit_secret_temp_dotenv.path is defined
