---

- name: Create runtime PostgreSQL users
  vars:
    pg_user: '{{ item.user }}'
    pg_pass: '{{ item.pass }}'
  community.postgresql.postgresql_user:
    name: '{{ pg_user }}'
    password: '{{ pg_pass }}'
    role_attr_flags: "{{ item.role_attr_flags | default('CREATEDB', true) }}"
    login_user: '{{ runtime_pg_admin_user }}'
    login_password: '{{ runtime_pg_admin_pass }}'
    login_host: "{{ item.host | default(runtime_pg_host, true) }}"
    login_port: "{{ item.port | default(runtime_pg_port, true) }}"
    ssl_mode: "{{ item.sslmode | default(runtime_pg_ssl, true) }}"
  run_once: true
  no_log: '{{ runtime_nolog }}'
  loop: '{{ runtime_pg_base_items }}'
  loop_control:
    label: "{{ item.user | default('<missing-user>', true) }}"
  when:
    - runtime_enabled | bool
    - runtime_pg_provision_enabled | bool

- name: Create runtime PostgreSQL databases
  vars:
    pg_base: '{{ item.base }}'
    pg_user: '{{ item.user }}'
  community.postgresql.postgresql_db:
    name: '{{ pg_base }}'
    owner: '{{ pg_user }}'
    encoding: UTF-8
    template: template0
    login_user: '{{ runtime_pg_admin_user }}'
    login_password: '{{ runtime_pg_admin_pass }}'
    login_host: "{{ item.host | default(runtime_pg_host, true) }}"
    login_port: "{{ item.port | default(runtime_pg_port, true) }}"
    ssl_mode: "{{ item.sslmode | default(runtime_pg_ssl, true) }}"
  run_once: true
  no_log: '{{ runtime_nolog }}'
  loop: '{{ runtime_pg_base_items }}'
  loop_control:
    label: "{{ item.base | default('<missing-base>', true) }}"
  when:
    - runtime_enabled | bool
    - runtime_pg_provision_enabled | bool
