---

- name: Create runtime secret directory
  become: true
  ansible.builtin.file:
    path: /home/{{ item.name }}/secrets
    state: directory
    mode: '0750'
    owner: '{{ item.name }}'
    group: '{{ item.name }}'
  loop: '{{ runtime_selected_apps }}'
  loop_control:
    label: '{{ item.name }}'
  when: runtime_enabled | bool

- name: Create runtime secrets for each environment
  become: true
  ansible.builtin.copy:
    content: '{{ item.secrets | to_nice_json }}'
    dest: '/home/{{ item.app }}/secrets/{{ runtime_cluster_realm }}_{{ item.env }}_{{ item.service }}.json'
    mode: '0600'
    owner: '{{ item.app }}'
    group: '{{ item.app }}'
    backup: '{{ runtime_secret_file_backup_mode | bool }}'
    force: '{{ runtime_secret_file_force_mode | bool }}'
  no_log: '{{ runtime_nolog }}'
  loop: '{{ runtime_secret_items }}'
  loop_control:
    label: '{{ item.app }}_{{ runtime_cluster_realm }}_{{ item.env }}_{{ item.service }}'
  when: runtime_enabled | bool
