---

- name: List runtime unit Docker secrets
  become: true
  ansible.builtin.command:
    cmd: "docker secret ls --format '{{ '{{' }}.Name{{ '}}' }}'"
  register: runtime_unit_docker_secret_list
  check_mode: false
  changed_when: false
  no_log: '{{ runtime_nolog }}'
  when:
    - runtime_enabled | bool
    - runtime_unit_secret_items | length > 0

- name: Capture runtime unit Docker secret timetag
  ansible.builtin.command:
    cmd: date -u +%y%m%d%H%M%S
  register: runtime_unit_secret_timetag
  check_mode: false
  changed_when: false
  no_log: '{{ runtime_nolog }}'
  when:
    - runtime_enabled | bool
    - runtime_unit_secret_items | length > 0

- name: Create runtime unit Docker secrets
  become: true
  vars:
    runtime_unit_secret_content: "{{ lookup('ansible.builtin.template', role_path ~ '/templates/runtime_secret.env.j2') }}"
    runtime_unit_secret_hash: "{{ (runtime_unit_secret_content | hash('sha256'))[:12] }}"
    runtime_unit_secret_prefix: '{{ item.app }}-{{ runtime_cluster_realm }}-{{ item.env }}-{{ item.unit }}'
    runtime_unit_secret_latest: >-
      {{
        runtime_unit_docker_secret_list.stdout_lines
        | default([], true)
        | select('match', '^' ~ runtime_unit_secret_prefix ~ '-[0-9]{12}-[0-9a-f]{12}$')
        | sort
        | last
        | default('', true)
      }}
    runtime_unit_secret_latest_hash: "{{ runtime_unit_secret_latest | regex_replace('^.*-', '') }}"
    runtime_unit_secret_name: '{{ runtime_unit_secret_prefix }}-{{ runtime_unit_secret_timetag.stdout }}-{{ runtime_unit_secret_hash }}'
  community.docker.docker_secret:
    name: '{{ runtime_unit_secret_name }}'
    data: '{{ runtime_unit_secret_content }}'
    state: present
  no_log: '{{ runtime_nolog }}'
  loop: '{{ runtime_unit_secret_items }}'
  loop_control:
    label: '{{ item.app }}-{{ runtime_cluster_realm }}-{{ item.env }}-{{ item.unit }}'
  when:
    - runtime_enabled | bool
    - runtime_unit_secret_latest_hash != runtime_unit_secret_hash
