---

- name: Restart rsyslog
  become: true
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Verify rsyslog service is active after restart
  become: true
  ansible.builtin.command:
    argv:
      - systemctl
      - is-active
      - rsyslog
  register: haproxy_rsyslog_restart_service_health
  changed_when: false
  listen: Restart rsyslog
