---

docker_redis_command: ''
docker_redis_container_name: redis
docker_redis_data_volume: redis-data
docker_redis_healthcheck_enabled: true
docker_redis_hostname: redis
docker_redis_image_name: redis
docker_redis_image_tag: ~
docker_redis_image_full: '{{ docker_redis_image_name }}:{{ docker_redis_image_tag }}'
docker_redis_mem_res: 200M
docker_redis_mem_lim: 300M
docker_redis_mem_swp: 400M
docker_redis_port: 6379
