---

- name: Assert Tempo required variables are set
  ansible.builtin.assert:
    that:
      - docker_tempo_cluster_name is not none
      - docker_tempo_cluster_name | string | length > 0
      - docker_tempo_cluster_platform is not none
      - docker_tempo_cluster_platform | string | length > 0
      - docker_tempo_cluster_realm is not none
      - docker_tempo_cluster_realm | string | length > 0
      - docker_tempo_image_tag is not none
      - docker_tempo_image_tag | string | length > 0
      - docker_tempo_init_image_tag is not none
      - docker_tempo_init_image_tag | string | length > 0
    fail_msg: Define Tempo cluster labels before running role docker_tempo.
