---

- name: Configure sysctl
  become: true
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    reload: true
  loop: '{{ base_hardening_sysctl_config }}'
