---

- name: Assert base hardening variable contract
  ansible.builtin.assert:
    that:
      - base_hardening_user_process_persistence_enabled | type_debug == 'bool'
      - base_hardening_ssh_port | string | length > 0
      - base_hardening_ssh_users is iterable
      - base_hardening_ssh_users is not string
      - base_hardening_sysctl_config is iterable
      - base_hardening_sysctl_config is not string
    fail_msg: Define base_hardening_* variables before running role base_hardening.
