---

- name: Assert Docker required variables are set
  ansible.builtin.assert:
    that:
      - docker_deb_repo | string | length > 0
      - docker_mirrors is sequence
      - docker_mirrors is not string
      - docker_force_mode | type_debug == 'bool'
      - docker_interactive_mode | type_debug == 'bool'
      - docker_arch_map is mapping
      - docker_dpkg_arch | string | length > 0
    fail_msg: Define valid Docker repository, mirror, force mode, interactive mode, and architecture settings before running role docker.
