---

docker_valkey_command: ''
docker_valkey_container_name: valkey
docker_valkey_data_volume: valkey-data
docker_valkey_healthcheck_enabled: true
docker_valkey_hostname: valkey
docker_valkey_image_name: valkey/valkey
docker_valkey_image_tag: ~
docker_valkey_image_full: '{{ docker_valkey_image_name }}:{{ docker_valkey_image_tag }}'
docker_valkey_mem_res: 200M
docker_valkey_mem_lim: 300M
docker_valkey_mem_swp: 400M
docker_valkey_port: 6379
