---

postgres_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
postgres_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
postgres_nolog: '{{ (postgres_ci_mode | bool) and not (postgres_debug_mode | bool) }}'
postgres_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
postgres_key_fingerprint: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
postgres_key_asc_path: /usr/share/keyrings/postgresql-archive-keyring.asc
postgres_keyring_path: /usr/share/keyrings/postgresql-archive-keyring.gpg
postgres_apt_repo_url: http://apt.postgresql.org/pub/repos/apt
postgres_apt_repo_distribution: '{{ ansible_distribution_release | lower }}-pgdg'
postgres_apt_repo_component: main
postgres_pg_admin_pass: ''
postgres_pg_admin_user: ''
postgres_version: 18
