---

docker_swarm_postgres_exporter_service_name: postgres-exporter
docker_swarm_postgres_exporter_ci_mode: "{{ lookup('env', 'CI') | default('0', true) in ['1', 'true'] }}"
docker_swarm_postgres_exporter_debug_mode: "{{ lookup('env', 'DEBUG') | default('0', true) in ['1', 'true'] }}"
docker_swarm_postgres_exporter_nolog: '{{ (docker_swarm_postgres_exporter_ci_mode | bool) and not (docker_swarm_postgres_exporter_debug_mode | bool) }}'
docker_swarm_postgres_exporter_image_name: quay.io/prometheuscommunity/postgres-exporter
docker_swarm_postgres_exporter_image_tag: v0.19.1
docker_swarm_postgres_exporter_image_full: '{{ docker_swarm_postgres_exporter_image_name }}:{{ docker_swarm_postgres_exporter_image_tag }}'
docker_swarm_postgres_exporter_mem_res: 100M
docker_swarm_postgres_exporter_mem_lim: 150M
docker_swarm_postgres_exporter_placement_constraints: []
docker_swarm_postgres_exporter_pg_base: ~
docker_swarm_postgres_exporter_pg_user: ~
docker_swarm_postgres_exporter_pg_pass: ~
docker_swarm_postgres_exporter_pg_host: ~
docker_swarm_postgres_exporter_pg_port: 5432
docker_swarm_postgres_exporter_pg_ssl: disable
docker_swarm_postgres_exporter_pg_admin_user: ''
docker_swarm_postgres_exporter_pg_admin_pass: ''
docker_swarm_postgres_exporter_public_port: 9187
docker_swarm_postgres_exporter_enabled: true
