---

- name: Assert PostgreSQL required variables are set
  ansible.builtin.assert:
    that:
      - postgres_version | int > 0
    fail_msg: Define valid PostgreSQL settings before running role postgres.
  no_log: '{{ postgres_nolog }}'
