---

docker_loki_image_name: grafana/loki
docker_loki_image_tag: 3.7.2
docker_loki_image_full: '{{ docker_loki_image_name }}:{{ docker_loki_image_tag }}'
docker_loki_grpc_listen_port: 3099
docker_loki_http_listen_port: 3100
docker_loki_alertmanager_host: localhost
docker_loki_alertmanager_port: 9093
docker_loki_config_template: loki-config.yaml.j2
docker_loki_mem_res: 1000M
docker_loki_mem_lim: 1500M
docker_loki_mem_swp: 2000M
