---

docker_ctop_version: 0.7.7
docker_ctop_download_base_url: https://github.com/bcicen/ctop/releases/download
docker_ctop_arch_map:
  aarch64: arm64
  armv7l: arm
  ppc64le: ppc64le
  x86_64: amd64
docker_ctop_arch: '{{ docker_ctop_arch_map.get(ansible_architecture, ansible_architecture) }}'
docker_ctop_binary_name: ctop-{{ docker_ctop_version }}-linux-{{ docker_ctop_arch }}
docker_ctop_binary_path: /usr/local/bin/ctop
docker_ctop_binary_checksum: sha256:{{ docker_ctop_download_base_url }}/v{{ docker_ctop_version }}/sha256sums.txt
docker_ctop_cache_dir: "{{ lookup('env', 'HOME') }}/.cache/apexplane-control/docker_ctop"
docker_ctop_cache_path: '{{ docker_ctop_cache_dir }}/{{ docker_ctop_binary_name }}'
